In [4]:
pip install numpy

                                              0.0/15.0 MB ? eta -:--:--
                                              0.0/15.0 MB ? eta -:--:--
                                             0.0/15.0 MB 325.1 kB/s eta 0:00:47
                                             0.1/15.0 MB 901.1 kB/s eta 0:00:17
     -                                        0.5/15.0 MB 2.6 MB/s eta 0:00:06
     ---                                      1.2/15.0 MB 5.2 MB/s eta 0:00:03
     -------                                  2.7/15.0 MB 9.6 MB/s eta 0:00:02
     -----------                              4.2/15.0 MB 12.7 MB/s eta 0:00:01
     ---------------                          5.8/15.0 MB 15.3 MB/s eta 0:00:01
     -------------------                      7.2/15.0 MB 17.7 MB/s eta 0:00:01
     ---------------------                    8.0/15.0 MB 18.3 MB/s eta 0:00:01
     ---------------------                    8.0/15.0 MB 18.3 MB/s eta 0:00:01
     --------------------------              10.1/15.0 MB 1

In [9]:
import numpy as np
arr=np.array([10,15,18,20,25])
print('1-D, Array is')
print(arr)
print('*'*25)
print(type(arr))
print(arr.dtype)

1-D, Array is
[10 15 18 20 25]
*************************
<class 'numpy.ndarray'>
int32


In [6]:
import numpy
arr=numpy.array([10,15.1,18+4j,20,25])
print('1-D, Array is')
print(arr)
print('*'*25)
print(type(arr))
print(arr.dtype)

1-D, Array is
[10. +0.j 15.1+0.j 18. +4.j 20. +0.j 25. +0.j]
*************************
<class 'numpy.ndarray'>
complex128


In [12]:
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

(5,)
1
5
int32
4


In [14]:
import numpy as mp
ar = np.arange(11)
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [19]:
ar = np.append(ar1,11)
print(ar)

NameError: name 'ar1' is not defined

In [29]:
# Statiscal Operation
arr=np.arange(7)
print(np.sqrt(arr))
print(np.std(arr))
print(np.exp(arr))
print(np.mean(arr))
print(np.median(arr))


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974]
2.0
[  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591  403.42879349]
3.0
3.0


In [32]:
# Arithmetic operators
a=np.arange(6)
b=np.arange(6,12)
print('Addition', a+b)
print('Subraction', a-b)
print('Multiplication', a*b)
print('Division', a/b)
print('Float Division', a//b)


Addition [ 6  8 10 12 14 16]
Subraction [-6 -6 -6 -6 -6 -6]
Multiplication [ 0  7 16 27 40 55]
Division [0.         0.14285714 0.25       0.33333333 0.4        0.45454545]
Float Division [0 0 0 0 0 0]


In [34]:
zero=np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [47]:
arr_2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.sqrt(arr_2d))
print(np.std(arr_2d))
print(np.exp(arr_2d))
print(np.mean(arr_2d))
print(np.median(arr_2d))

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]]
2.8722813232690143
[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
  1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03
  2.20264658e+04]]
5.5
5.5


In [35]:
one=np.ones(10)
print(one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [37]:
#reshape and resize
ar_rs=np.arange(12).reshape(4,3)
print(ar_rs)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [43]:
ar_rs.resize(3,4)
print(ar_rs)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [46]:
ar_rs.resize(2,6)
print(ar_rs)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [51]:
arr=np.array([[0,1],[2,3]])
print(arr)
print('*'*25)
arr2=np.resize(arr,(3,2))
print(arr2)

[[0 1]
 [2 3]]
*************************
[[0 1]
 [2 3]
 [0 1]]


# Create array to play on

In [2]:
import numpy as np
array = np.arange(15).reshape(5,3)
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [4]:
array.sum()

105

In [5]:
array.sum(axis=0)

array([30, 35, 40])

In [6]:
array.sum(axis=1)

array([ 3, 12, 21, 30, 39])

In [7]:
array.max()

14

In [8]:
array.max(axis=0)

array([12, 13, 14])

In [10]:
array.argmax(axis=0)

array([4, 4, 4], dtype=int64)

In [12]:
print(array[0])
print(array[4])

[0 1 2]
[12 13 14]


# Variance and Standard Deviation function (Statiscal function)

In [18]:
array=np.arange(1,7)
array

array([1, 2, 3, 4, 5, 6])

In [19]:
array.var()

2.9166666666666665

In [20]:
array.std()

1.707825127659933

In [21]:
print(np.sqrt(array.var()))

1.707825127659933


#  Numpy Array indexing and Selection

In [22]:
array = np.arange(15).reshape(5,3)
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [26]:
print(array[:2, :2])

[[0 1]
 [3 4]]


In [28]:
print(array[1: , 1:])

[[ 4  5]
 [ 7  8]
 [10 11]
 [13 14]]


In [29]:
print(array[1][1])

4


In [30]:
print(array[3][2])

11


In [31]:
print(array[0:4])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


# COPY

In [34]:
arr=np.arange(11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [35]:
copy_arr = arr[0:3].copy()
print(copy_arr)

[0 1 2]


In [36]:
copy_arr[:] = 22
copy_arr

array([22, 22, 22])

# Selection

In [38]:
arr=np.arange(13)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [40]:
part_arr=arr[7:11]
part_arr[:] = 99
part_arr

array([99, 99, 99, 99])

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6, 99, 99, 99, 99, 11, 12])

In [42]:
arr>45

array([False, False, False, False, False, False, False,  True,  True,
        True,  True, False, False])

In [43]:
filter_arr=arr>45

In [45]:
filter_arr

array([False, False, False, False, False, False, False,  True,  True,
        True,  True, False, False])

In [46]:
arr[filter_arr]

array([99, 99, 99, 99])

# Creating arrays with random

In [1]:
import numpy.random as rd

In [2]:
rd.random(10)

array([0.02757768, 0.33938495, 0.63496776, 0.69622932, 0.9456069 ,
       0.98768232, 0.53846325, 0.02210993, 0.14174747, 0.47252109])

In [4]:
#randin  - it will display the positive and negative
sort_ar = rd.randin(12).reshape(3,4)

AttributeError: module 'numpy.random' has no attribute 'randin'